name: Mock Test
on: [push]
jobs:
  Mock_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod vendor

      - name: Build smart-contract as a plugin
        run: go build -buildmode=plugin -o smart-contract.so -ldflags "-s -w" ./smart-contract.go

      - name: Execute test
        run: go test -v --count=1 .
