name: Mock Test
on: [push]
jobs:
  Mock_Test:
    runs-on: golang:1.18
    steps:
      - run: go mod vendor
      - run: go build -buildmode=plugin -o smart-contract.so -ldflags "-s -w" ./smart-contract.go
      - run: go test -v --count=1 .
